
import { propertyData } from "@/app/types/property/propertyData";
import { NextResponse } from "next/server";

const property: propertyData[] = [
  // Apartamento
  {
    id: '1',
    property_img: "/images/properties/prop-1.jpg",
    property_title: "Apartamento Moderno",
    property_price: "$150,000",
    category: "apartamento",
    category_img: "/images/property_option/apartment.svg",
    rooms: 2,
    bathrooms: 1,
    location: "California",
    livingArea: "85m²",
    tag: "Venta",
    check: true,
    status: "Comprar",
    type: "Apartamento",
    beds: 2,
    garages: 0,
    region: "sur",
    name: "Propiedad 1",
    slug: "apartamento-moderno"
  },
  {
    id: '2',
    property_img: "/images/properties/prop-2.jpg",
    property_title: "Apartamento en la Ciudad",
    property_price: "$180,000",
    category: "apartamento",
    category_img: "/images/property_option/apartment.svg",
    rooms: 3,
    bathrooms: 2,
    location: "Texas",
    livingArea: "110m²",
    tag: "Comprar",
    check: true,
    status: "Comprar",
    type: "Apartamento",
    beds: 3,
    garages: 1,
    region: "norte",
    name: "Propiedad 2",
    slug: "apartamento-ciudad"
  },
  {
    id: '3',
    property_img: "/images/properties/prop-3.jpg",
    property_title: "Apartamento de Lujo",
    property_price: "$220,000",
    category: "apartamento",
    category_img: "/images/property_option/apartment.svg",
    rooms: 4,
    bathrooms: 3,
    location: "Nueva York",
    livingArea: "140m²",
    tag: "Venta",
    check: true,
    status: "Comprar",
    type: "Apartamento",
    beds: 4,
    garages: 1,
    region: "este",
    name: "Propiedad 3",
    slug: "apartamento-lujo"
  },

  // Villa
  {
    id: '4',
    property_img: "/images/properties/prop-4.jpg",
    property_title: "Villa Mithra",
    property_price: "$200,000",
    category: "villa",
    category_img: "/images/property_option/villa.svg",
    rooms: 3,
    bathrooms: 2,
    location: "Florida",
    livingArea: "190m²",
    tag: "Comprar",
    check: true,
    status: "Comprar",
    type: "Villa",
    beds: 3,
    garages: 1,
    region: "norte",
    name: "Propiedad 4",
    slug: "villa-mithra"
  },
  {
    id: '5',
    property_img: "/images/properties/prop-5.jpg",
    property_title: "Villa algo",
    property_price: "$250,000",
    category: "villa",
    category_img: "/images/property_option/villa.svg",
    rooms: 4,
    bathrooms: 3,
    location: "Illinois",
    livingArea: "210m²",
    tag: "Venta",
    check: false,
    status: "Comprar",
    type: "Villa",
    beds: 4,
    garages: 2,
    region: "oeste",
    name: "Propiedad 5",
    slug: "villa-palm"
  },
  {
    id: '6',
    property_img: "/images/properties/prop-6.jpg",
    property_title: "Villa Sunset",
    property_price: "$275,000",
    category: "villa",
    category_img: "/images/property_option/villa.svg",
    rooms: 5,
    bathrooms: 4,
    location: "California",
    livingArea: "250m²",
    tag: "Comprar",
    check: true,
    status: "Comprar",
    type: "Villa",
    beds: 5,
    garages: 2,
    region: "sur",
    name: "Propiedad 6",
    slug: "villa-sunset"
  },

  // Oficina
  {
    id: '7',
    property_img: "/images/properties/prop-7.jpg",
    property_title: "Oficina Centro",
    property_price: "$320,000",
    category: "oficina",
    category_img: "/images/property_option/office.svg",
    rooms: 6,
    bathrooms: 2,
    location: "Texas",
    livingArea: "300m²",
    tag: "Venta",
    check: true,
    status: "Comprar",
    type: "Comercial",
    beds: 2,
    garages: 2,
    region: "centro",
    name: "Propiedad 7",
    slug: "oficina-centro"
  },
  {
    id: '8',
    property_img: "/images/properties/prop-8.jpg",
    property_title: "Oficina IT",
    property_price: "$400,000",
    category: "oficina",
    category_img: "/images/property_option/office.svg",
    rooms: 10,
    bathrooms: 4,
    location: "Nueva York",
    livingArea: "500m²",
    tag: "Comprar",
    check: true,
    status: "Comprar",
    type: "Comercial",
    beds: 2,
    garages: 4,
    region: "norte",
    name: "Propiedad 8",
    slug: "oficina-it"
  },
  {
    id: '9',
    property_img: "/images/properties/prop-9.jpg",
    property_title: "Centro de Startups",
    property_price: "$350,000",
    category: "oficina",
    category_img: "/images/property_option/office.svg",
    rooms: 8,
    bathrooms: 3,
    location: "Florida",
    livingArea: "420m²",
    tag: "Venta",
    check: true,
    status: "Comprar",
    type: "Comercial",
    beds: 1,
    garages: 3,
    region: "este",
    name: "Propiedad 9",
    slug: "centro-startups"
  },

  // Tienda
  {
    id: '10',
    property_img: "/images/properties/prop-10.jpg",
    property_title: "Tienda Minorista",
    property_price: "$120,000",
    category: "tienda",
    category_img: "/images/property_option/shop.svg",
    rooms: 2,
    bathrooms: 1,
    location: "Illinois",
    livingArea: "60m²",
    tag: "Comprar",
    check: true,
    status: "Comprar",
    type: "Comercial",
    beds: 1,
    garages: 0,
    region: "oeste",
    name: "Propiedad 10",
    slug: "tienda-minorista"
  },
  {
    id: '11',
    property_img: "/images/properties/prop-11.jpg",
    property_title: "Tienda de Esquina",
    property_price: "$140,000",
    category: "tienda",
    category_img: "/images/property_option/shop.svg",
    rooms: 3,
    bathrooms: 1,
    location: "California",
    livingArea: "75m²",
    tag: "Venta",
    check: true,
    status: "Comprar",
    type: "Comercial",
    beds: 3,
    garages: 1,
    region: "sur",
    name: "Propiedad 11",
    slug: "tienda-esquina"
  },
  {
    id: '12',
    property_img: "/images/properties/prop-12.jpg",
    property_title: "Unidad Comercial",
    property_price: "$160,000",
    category: "tienda",
    category_img: "/images/property_option/shop.svg",
    rooms: 4,
    bathrooms: 1,
    location: "Texas",
    livingArea: "90m²",
    tag: "Comprar",
    check: true,
    status: "Comprar",
    type: "Comercial",
    beds: 1,
    garages: 1,
    region: "este",
    name: "Propiedad 12",
    slug: "unidad-comercial"
  },

  // Casa
  {
    id: '13',
    property_img: "/images/properties/prop-13.jpg",
    property_title: "Casa Clásica",
    property_price: "$180,000",
    category: "casa",
    category_img: "/images/property_option/house.svg",
    rooms: 4,
    bathrooms: 2,
    location: "Nueva York",
    livingArea: "160m²",
    tag: "Venta",
    check: true,
    status: "Comprar",
    type: "Casa",
    beds: 4,
    garages: 1,
    region: "norte",
    name: "Propiedad 13",
    slug: "casa-clasica"
  },
  {
    id: '14',
    property_img: "/images/properties/prop-14.jpg",
    property_title: "Casa Familiar",
    property_price: "$190,000",
    category: "casa",
    category_img: "/images/property_option/house.svg",
    rooms: 5,
    bathrooms: 3,
    location: "Florida",
    livingArea: "180m²",
    tag: "Comprar",
    check: true,
    status: "Comprar",
    type: "Casa",
    beds: 5,
    garages: 1,
    region: "oeste",
    name: "Propiedad 14",
    slug: "casa-familiar"
  },
  {
    id: '15',
    property_img: "/images/properties/prop-15.jpg",
    property_title: "Casa Compacta",
    property_price: "$160,000",
    category: "casa",
    category_img: "/images/property_option/house.svg",
    rooms: 3,
    bathrooms: 2,
    location: "Illinois",
    livingArea: "120m²",
    tag: "Venta",
    check: true,
    status: "Comprar",
    type: "Casa",
    beds: 3,
    garages: 1,
    region: "sur",
    name: "Propiedad 15",
    slug: "casa-compacta"
  },

  // Bodega
  {
    id: '16',
    property_img: "/images/properties/prop-16.jpg",
    property_title: "Bodega Industrial",
    property_price: "$500,000",
    category: "bodega",
    category_img: "/images/property_option/warehouse.svg",
    rooms: 2,
    bathrooms: 1,
    location: "California",
    livingArea: "1000m²",
    tag: "Comprar",
    check: true,
    status: "Comprar",
    type: "Comercial",
    beds: 2,
    garages: 2,
    region: "centro",
    name: "Propiedad 16",
    slug: "bodega-industrial"
  },
  {
    id: '17',
    property_img: "/images/properties/prop-17.jpg",
    property_title: "Unidad de Almacenamiento",
    property_price: "$450,000",
    category: "bodega",
    category_img: "/images/property_option/warehouse.svg",
    rooms: 1,
    bathrooms: 1,
    location: "Texas",
    livingArea: "800m²",
    tag: "Comprar",
    check: true,
    status: "Comprar",
    type: "Comercial",
    beds: 4,
    garages: 1,
    region: "norte",
    name: "Propiedad 17",
    slug: "unidad-almacenamiento"
  },
  {
    id: '18',
    property_img: "/images/properties/prop-18.jpg",
    property_title: "Centro Logístico",
    property_price: "$600,000",
    category: "bodega",
    category_img: "/images/property_option/warehouse.svg",
    rooms: 3,
    bathrooms: 2,
    location: "Nueva York",
    livingArea: "1200m²",
    tag: "Comprar",
    check: true,
    status: "Comprar",
    type: "Comercial",
    beds: 5,
    garages: 3,
    region: "este",
    name: "Propiedad 18",
    slug: "centro-logistico"
  }
];

export async function GET() {
  return NextResponse.json(property);
}
